item_stat_boosts = {
    # Right/Left Hand
    "Wooden Sword": {"strength": +2},
    "Iron Sword": {"strength": +5},
    "Steel Greatsword": {"strength": +8, "endurance": -1},
    "Torch": {"intelligence": +1},
    "Wooden Stick": {"strength": +1},
    "Wand of Sparks": {"intelligence": +4},
    "Dagger": {"strength": +2, "endurance": +1},
    "Shield": {"defense": +4, "strength": -1},
    "Crossbow": {"strength": +3, "endurance": -2},
    "Spear": {"strength": +4, "defense": +1},
    "Shadow Dagger": {"strength": +3, "intelligence": +2},
    "Sword of Flames": {"strength": +6, "intelligence": +1, "magic": +2},
    "Staff of Wisdom": {"magic": +5, "endurance": +2},
    "Battle Axe": {"strength": +7, "endurance": -1, "defense": +2},
    "Battle Hammer": {"strength": +6, "defense": +2, "endurance": -1},
    "Obsidian Blade": {"strength": +10, "endurance": -2},
    "Arcane Staff": {"intelligence": +6, "endurance": +1},
    "Iron Mace": {"strength": +4, "defense": +2},
    "Hunter's Bow": {"strength": +3, "endurance": +2},
    "Fire Wand": {"intelligence": +5, "strength": +1},
    "Mirror Shield": {"defense": +5, "intelligence": +2},
    "Cursed Blade": {"strength": +8, "intelligence": -2},
    "Runic Sword": {"strength": +4, "intelligence": +3},
    "Merlin's Wand": {"magic": +7, "endurance": +1, "intelligence": +3},
    "Shadow Blade": {"strength": +5, "intelligence": +2},
    "Arthur Pendragon's Sword": {"strength": +9, "defense": +2, "endurance": +1},


    # Helmet
    "Helmet of Resilience": {"defense": +2},
    "Mage Hood": {"intelligence": +3},
    "Horned Helm": {"strength": +2, "defense": +1},
    "Thief's Cowl": {"endurance": +2, "intelligence": +1},
    "Iron Mask": {"defense": +3},
    "Wizard's Hat": {"magic": +4, "endurance": +1},
    "Knight's Helm": {"defense": +5, "strength": +1},
    "Cursed Mask": {"intelligence": +2, "defense": -1},
    "Crown of Insight": {"intelligence": +4, "defense": +1},
    "Iron Helm": {"defense": +3},
    "Veil of Shadows": {"intelligence": +2, "endurance": +2},
    "Headband of Fury": {"strength": +3},



    # Chestplate
    "Iron Chestplate": {"defense": +5},
    "Robe of Focus": {"intelligence": +3, "endurance": +1},
    "Leather Vest": {"endurance": +2, "defense": +1},
    "Dragon Scale Armor": {"defense": +7, "strength": +2},
    "Mage's Robe": {"magic": +5, "endurance": -1},
    "Plate Armor": {"defense": +6, "strength": +1},
    "Cloak of Shadows": {"intelligence": +2, "endurance": +2},
    "Enchanted Cuirass": {"defense": +4, "intelligence": +2},
    "Hunter's Tunic": {"endurance": +3, "strength": +1},
    "Battle Robe": {"strength": +2, "intelligence": +2},
    "Crimson Plate": {"defense": +6, "strength": +1},
    "Mystic Robe": {"magic": +3, "endurance": +2},
    "Shadow Armor": {"intelligence": +3, "endurance": +1, "defense": +2},
    "Titanium Chestplate": {"defense": +8, "strength": +2},
    "Leather Armor": {"endurance": +1, "defense": +2},

    # Leggings
    "Iron Greaves": {"defense": +3},
    "Robes of Agility": {"endurance": +2},
    "Leggings of Might": {"strength": +3},
    "Leather Pants": {"endurance": +1},
    "Chainmail Leggings": {"defense": +4, "strength": +1},
    "Mystic Leggings": {"magic": +2, "endurance": +1},
    "Shadow Pants": {"intelligence": +2, "endurance": +2},
    "Greaves of Grounding": {"defense": +4, "intelligence": -1},
    "Leggings of Wind": {"endurance": +4},
    "Mystic Pants": {"intelligence": +3, "endurance": +1},
    "Soldier's Leggings": {"strength": +2, "defense": +2},


    # Boots
    "Boots of Speed": {"endurance": +2},
    "Iron Boots": {"defense": +2},
    "Sneakers of Stealth": {"endurance": +2, "intelligence": +1},
    "Plated Boots": {"defense": +3, "endurance": -1},
    "Leather Boots": {"endurance": +1},
    "Mystic Boots": {"magic": +2, "endurance": +1},
    "Shadow Boots": {"intelligence": +2, "endurance": +2},
    "Boots of Leaping": {"endurance": +3},
    "Iron-Tread Boots": {"defense": +3},
    "Ghoststep Boots": {"intelligence": +1, "endurance": +2},
    "Runic Boots": {"intelligence": +2, "defense": +1},

    # Accessories
    "Amulet of Wisdom": {"intelligence": +5},
    "Ring of Power": {"strength": +3},
    "Bracelet of Fortitude": {"defense": +2, "endurance": +1},
    "Talisman of Clarity": {"intelligence": +2, "defense": +1},
    "Charm of The Fox": {"endurance": +3, "intelligence": +1},
    "Ring of Agility": {"endurance": +2},
    "Amulet of Strength": {"strength": +4},
    "Ring of Intelligence": {"intelligence": +4},
    "Amulet of Defense": {"defense": +3},
    "Ring of Endurance": {"endurance": +3},
    "Amulet of Magic": {"magic": +3},
    "Ring of Resilience": {"defense": +3},
    "Pendant of Vigor": {"endurance": +4},
    "Crystal Earring": {"intelligence": +3},
    "Warrior's Band": {"strength": +4},
    "Shadow Charm": {"intelligence": +2, "endurance": +2},
    "Sunstone Brooch": {"strength": +2, "defense": +1},
    "Elven Locket": {"intelligence": +3, "endurance": +1, "magic": +2},
    "Tarnished Silver Ring": {"strength": +1, "defense": +1, "magic": +1},
    "Necklace of Agility": {"endurance": +2, "strength": +1},

}
